#H2 \uba54\ubaa8\ub9ac \ub370\uc774\ud130\ubca0\uc774\uc2a4\uc778 testdb \ub97c \uc0dd\uc131\ud558\ub294\u2026 \uc544\ub798 4\uc904\ub9cc application-db-h2.properties \ud30c\uc77c\ub85c \uc774\ub3d9
spring.datasource.url=jdbc:h2:mem:testdb;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
#H2 \uba54\ubaa8\ub9ac DB\uc5d0 \ucd08\uae30 \uc0ac\uc6a9\uc790 \uac12 \ucd94\uac00 
spring.jpa.defer-datasource-initialization=true
spring.sql.init.schema-locations=classpath:import_h2db_only.sql