#Datasource \uc124\uc815 \ucd94\uac00
spring.datasource.sql-script-encoding=utf-8
spring.datasource.initialization-mode=always
spring.datasource.platform=postgres
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d6drniktgctc73ch6fmg-a.singapore-postgres.render.com/postgresql_z6tu 
#\uc8fc\uc18c jdbc:postgresql://\ub85c \uc2dc\uc791\ud558\ub294 \ubd80\ubd84\uc744 \uc8fc\uc758\ud55c\ub2e4.
spring.datasource.username=postgresql_z6tu_user
spring.datasource.password=33V5oQpE1LsWTQn88AOQPr5WgMms6rnM
#JPA \uc138\uc158\uc124\uc815(\uc544\ub798 \uc138\uc158\ud14c\uc774\ube14 \uc0dd\uc131, \ub2e8\uc704 \ucd08, \uc138\uc158\uc720\uc9c0 30\ubd84)
server.session.timeout=1800
spring.session.jdbc.initializer.enabled=true
spring.session.jdbc.table-name=SPRING_SESSION
#\uc2a4\ud504\ub9c1 DB\uc138\uc158 \ub370\uc774\ud130 \uc800\uc7a5 \uc0ac\uc6a9(\uc544\ub798)
spring.session.store-type=jdbc
#\uc2a4\ud504\ub9c1 DB\uc138\uc158 \ud14c\uc774\ube14 \uc0dd\uc131 \ud55c\ub2e4.(\uc774 \ub77c\uc778\uc774 \uc5c6\uc73c\uba74 H2\ucc98\ub7fc \ub0b4\uc7a5\uba54\ubaa8\ub9ac DB\uc5d0\uc11c\ub9cc \uc0ac\uc6a9 \uac00\ub2a5\ud558\ub2e4.)
spring.session.jdbc.initialize-schema=always
#JPA \ud0c0\uc785 \uc124\uc815(\uc544\ub798\ub294 Postgres\uc6a9)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#\ucd5c\ucd08 \uc2e4\ud589\uc2dc \uae30\uc874 \ud14c\uc774\ube14 \uc0ad\uc81c \ud6c4 \uc0dd\uc131(\uc544\ub798 \ucd08\uae30\ud654)
spring.jpa.hibernate.ddl-auto=create
#2\ubc88\uc9f8 \ubc30\ud3ec\ubd80\ud130\ub294 \uc8fc\uc11d\ud574\uc81c \uc5c5\ub370\uc774\ud2b8\ub9cc \ud55c\ub2e4.(\uc544\ub798)
spring.jpa.hibernate.ddl-auto=update
#\uae30\ubcf8\uc124\uc815\ub41c jdbc\uba54\ud0c0 \ub370\uc774\ud130\ub97c \uc0ac\uc6a9\ud558\uc9c0 \uc54a\uace0, \uac1c\ubc1c\uc790 \ud658\uacbd\uad6c\uc131\uc744 \uc0ac\uc6a9\ud558\uaca0\ub2e4.(\uc544\ub798)
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
#JPA Debug \uc124\uc815 \ucd94\uac00(\uc544\ub798 \ucf58\uc194\uc5d0 \ucffc\ub9ac\ub0b4\uc6a9\uc744 \ubcf4\uae30 \ud3b8\ud558\uac8c \ubcf4\uc5ec\uc90c)
spring.jpa.properties.hibernate.format_sql=true

#spring.application.name=kimilguk-boot4
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

#\ub85c\uae45\ub808\ubca8(\ub9ce\uc740\ub0b4\uc6a9 \ucd9c\ub825\uc21c\uc11c): debug>info>warn>error \ub4f1
logging.level.root=info
#\ub85c\uae45\ub808\ubca8\uc744 \ucd95\uc18c\ud558\uba74\uc11c DB\uc2e4\ud589\uad6c\ubb38(SQL)\uc774 \ub098\uc624\uc9c0 \uc54a\uc544\uc11c \ucd94\uac00(\uc544\ub798)
spring.jpa.show_sql=true
#\ud654\uc774\ud2b8\ub77c\ubca8 \uc5d0\ub7ec\ud398\uc774\uc9c0 \uc0ac\uc6a9 \uc548\ud568.
server.error.whitelabel.enabled=FALSE
#\uc5d0\ub7ec \ubc1c\uc0dd\uc2dc \uc774\ub3d9\ud560 \uacbd\ub85c\ucd94\uac00
server.error.path=/error
#\ucca8\ubd80\ud30c\uc77c multipart \ud30c\uc77c\uc0ac\uc774\uc988 \uc9c0\uc815
spring.servlet.multipart.maxFileSize=100MB
#\ucca8\ubd80\ud30c\uc77c multipart \uc694\uccad\uc0ac\uc774\uc988 \uc9c0\uc815
spring.servlet.multipart.maxRequestSize=100MB
