#H2 \uba54\ubaa8\ub9ac \ub370\uc774\ud130\ubca0\uc774\uc2a4\uc778 testdb \ub97c \uc0dd\uc131\ud558\ub294\u2026 \uc544\ub798 4\uc904\ub9cc application-db-h2.properties \ud30c\uc77c\ub85c \uc774\ub3d9
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=